spring:
  application:
    name: "candidate"
  main:
    banner-mode: off
  profiles:
    active: "default"
  data:
    mongodb:
      authentication-database: admin
      database: candidate_db
      host: localhost
      port: 27027
  config:
    import: "optional:configserver:http://localhost:5000/"

logging:
  level:
    com:
      hoang:
        user: DEBUG