spring:
  application:
    name: "notification"
  main:
    banner-mode: off
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:5000/"

logging:
  level:
    com:
      hoang:
        gatewayserver: INFO
    netflix:
      discovery: WARN

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 75
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2